from tkinter import *
root = Tk()
root.geometry('300x700+10+1')
root.title('REX')
root.config(bg = '#17202A')
logo = PhotoImage(file = 'Logo.png')
logolabel = Label(root,image = logo, bg = '#17202A')
logolabel.pack()
frame = Frame(root)
frame.pack()
scroll = Scrollbar(frame)
scroll.pack(side=RIGHT)
txt = Text(frame, font= ('Segoe UI',20,'bold'), height=12,yscrollcommand=scroll.set,bg = '#17202A', wrap='word',fg = '#abb2b9')
txt.pack(side=LEFT)
scroll.config(command=txt.yview)
field = Entry(root, font=('Segoe UI',20,'bold'),bg = '#17202A',fg = '#abb2b9')
field.pack(pady=15, fill=X)
asklogo = PhotoImage(file = 'ask.png')
ask = Button(root, image = asklogo, bg = '#17202A',height = 50)
ask.pack()
root.mainloop() 

